controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    # forward_velocity_controller:
    #   type: forward_command_controller/ForwardCommandController

    # forward_position_controller:
    #   type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    ackermann_steering_controller:
      type: 'ackermann_steering_controller/AckermannSteeringController'

ackermann_steering_controller:
  ros__parameters:
    wheelbase: .275
    front_wheel_track: 1.0
    rear_wheel_track: 1.0
    front_wheels_radius: 0.0575
    rear_wheels_radius: 0.0575
    front_steering: true
    reference_timeout: 2.0
    rear_wheels_names: ['rear_right_wheel_joint', 'rear_left_wheel_joint']
    front_wheels_names: ['front_right_steering_joint', 'front_left_steering_joint']
    use_stamped_vel: true
    open_loop: false
    velocity_rolling_window_size: 10
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    position_feedback: false
